blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Определяет URL адреса для blogs"""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница заметок
    path('notes/', views.notes, name='notes'),
    # Добавление заметки
    path('new_note/', views.new_note, name='new_note'),
    # Редактирование заметки
    path('edit_note/<int:note_id>', views.edit_note, name='edit_note'),
]

users/urls.py
"""Определяет URL адреса для users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Шаблон выхода из аккаунта
    path('logout/', views.logout_view, name='logout'),
    # Включение ссылок аутентификации
    path('', include('django.contrib.auth.urls')),
    # Страница для регистрации аккаунта
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """Модель с полями заголовка и текста"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}
        # widgets = {'text': forms.Textarea(attrs={'cols': 80}), 'title': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogForm

def index(request):
    """Домашняя страница blog"""
    return render(request, 'blogs/index.html')

@login_required
def notes(request):
    """Выводит список заметок"""
    notes = BlogPost.objects.filter(owner=request.user).order_by('-date_added')
    context = {'notes': notes}
    return render(request, 'blogs/notes.html', context)

@login_required
def new_note(request):
    """Создает новую заметку"""
    if request.method != 'POST':
        # Данные не отправлялись; создается новая заметка
        form = BlogForm()
    else:
        # Данные отправлены; обработать их
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.owner = request.user
            new_form.save()
            return redirect('blogs:notes')
    
    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'blogs/new_note.html', context)

@login_required
def edit_note(request, note_id):
    """Редактирование заметки"""
    # Получает объект заметки.
    note = get_object_or_404(BlogPost, id=note_id)
    
    _check_note_owner(request, note)

    # Вывод заметки с хранящимися в ней данными
    if request.method != 'POST':
        form = BlogForm(instance=note)
    else:
        # Данные отправлены; обработать их
        form = BlogForm(instance=note, data=request.POST)
        if form.is_valid():
            edit_note = form.save(commit=False)
            edit_note.owner = request.user
            edit_note.save()
            return redirect('blogs:notes')
    
    # Вывести пустую или недействительную форму
    context = {'note': note, 'form': form}
    return render(request, 'blogs/edit_note.html', context)

def _check_note_owner(request, note):
    """Проверка того, что тема принадлежит текущему пользователю"""
    if note.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Данные не отправлялись; создается новая заметка
        form = UserCreationForm()
    else:
        # Данные отправлены; обработать данные
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:index')
    
    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'users/register.html', context)

def logout_view(request):
    """Выход из аккаунта пользователя"""
    if request.method == 'POST':
        logout(request)
        
    return render(request, 'users/logged_out.html')

blogs/templates/blogs/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <title>My blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  
  <body>
    <header class="position-relative border-bottom bg-light shadow-lg mb-4">
      <nav class="top-50 p-2">
        <a class="text-decoration-none fs-5" href="{% url 'blogs:index' %}">
          My blog</a> &raquo;
        <a class="text-decoration-none fs-5" href="{% url 'blogs:notes' %}">
          notes</a>
      </nav>
      <div class="position-absolute end-0 top-0 m-1">
        {% if user.is_authenticated %}
          <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            {% buttons %}
              <button class="btn btn-primary" type="submit">Log out</button>
            {% endbuttons %}
          </form>
        {% endif %}
        </div>
      </div>
    </header>

    <main class="container bg-light">
      <div class="border-bottom mb-3 pt-2">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
  </body>
</html>










  {% comment %} </head>
  <body>
    <header class="shadow-lg p-2 bg-light navbar-brand border-bottom mb-4">
      <nav>
        <div>
          <a class="text-secondary" href="{% url 'blogs:index' %}">My blog</a>
        </div>
        <div>
          <a class="text-secondary" href="{% url 'blogs:notes' %}">Notes</a>
        </div>
      </nav>
      <div>
        {% if user.is_authenticated %}
          <form method="post" action="{% url 'users:logout' %}">
          {% csrf_token %}
          <button type="submit">Log out</button>
        {% else %}
          <a href="{% url 'users:login' %}">Log in</a>
          <a href="{% url 'users:register' %}">Register</a>
        {% endif %}
      </div>
    </header>
    <main>
      <div>
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
</html> {% endcomment %}






{% comment %} <a href="{% url 'blogs:index' %}">Main page</a> -
<a href="{% url 'blogs:notes' %}">Notes</a> - 

{% if user.is_authenticated %}
  Hello, {{ user.username }}
  <form method="post" action="{% url 'users:logout' %}">
    {% csrf_token %}
  
  <p><button type="submit">Log out</button></p>
  </form>

{% else %}
  <a href="{% url 'users:register' %}">Register</a> -
  <a href="{% url 'users:login' %}">Log in</a>
{% endif %}

{%block content %}{% endblock content %} {% endcomment %}

blogs/templates/blogs/edit_note.html
{% extends 'blogs/base.html' %}
{% load bootstrap5 %}

{% block page_header %}
  <h3>
    Editing «{{ note.title }}»
  </h3>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'blogs:edit_note' note.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button class="btn btn-primary" type="submit">Edit note</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Make your own notes</h3>
    
    <p class="lead">You can comfortobly write down whatever you want
       and then return to your note.</p>
    
    <p>
      {% if not user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'users:register' %}"
          role="button">Register &raquo;</a>
        <a class="btn btn-primary" href="{% url 'users:login' %}"
          role="button">Log in &raquo;</a>
      {% else %}
        <h5>Hello, {{ user.username }}!</h5>
      {% endif %}
    </p>
  </div>
{% endblock page_header %}

blogs/templates/blogs/new_note.html
{% extends 'blogs/base.html' %}
{% load bootstrap5 %}

{% block page_header %}
  <h3>Adding a note</h3>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'blogs:new_note' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button class="btn btn-primary" type="submit">Add</button>
    {% endbuttons %}
  </form>
{% endblock content %}

blogs/templates/blogs/notes.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>Notes</h1>
{% endblock page_header %}

{% block content %}
  <a role="button" class="btn btn-primary text-decoration-none mb-3"
    href="{% url 'blogs:new_note' %}">Add a new note</a>

  {% for note in notes %}
    <div class="card mb-3">
      <div class="card-header">
        <a class="text-decoration-none" href="{% url 'blogs:edit_note' note.id %}">
          {{ note }}</a> | {{ note.date_added|date:'M d, Y H:i' }}
      </div>
      <div class="card-body">
        {{ note.text }}
      </div>
    </div>
  {% empty %}
    <h3>No notes have been added yet.</h3>
  {% endfor %}

{% endblock content %}

users/templates/users/logged_out.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h3>Log out</h3>

  <p>You have been successfully logged out!</p>
{% endblock page_header %}

users/templates/users/register.html
{% extends 'blogs/base.html' %}
{% load bootstrap5 %}

{% block page_header %}
  <h3>Register</h3>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button class="btn btn-primary" type="submit">Register</button>
      <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
    {% endbuttons %}
  </form>
{% endblock content %}